version: "3.7"

services:

  web:
    image: nginx:1.17
    ports:
      - 80:80
    volumes:
      - /home/ib/practice/study-docker/recipe-01/html:/var/www/myapp
      - /home/ib/practice/study-docker/recipe-01/docker/site.conf:/etc/nginx/conf.d/site.conf
