version: "3.7"

services:

  web:
    image: nginx:1.17
    ports:
      - 80:80
    volumes:
      - /var/www/docker-study.loc/recipe-02/php:/var/www/myapp
      - /var/www/docker-study.loc/recipe-02/docker/site.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - php

  php:
    image: php:7.2-fpm
    volumes:
      - /home/ib/practice/study-docker/recipe-01/html/recipe-02/php:/var/www/myapp
      - /home/ib/practice/study-docker/recipe-01/html/docker/php.ini:/usr/local/etc/php/php.ini